sudo: false
language: php
php:
 - "5.5"
 - "5.6"
 - "hhvm"
env:
 - YENTU_DRIVER=mysql YENTU_HOST=localhost YENTU_SKIP_SCHEMAS=yes YENTU_USER=root YENTU_BASE_DSN='mysql:host=localhost'
 - YENTU_DRIVER=postgresql YENTU_HOST=localhost YENTU_USER=postgres YENTU_DEFAULT_SCHEMA=public YENTU_BASE_DSN='pgsql:host=localhost'
 - YENTU_DRIVER=sqlite YENTU_FILE=sqlite.db YENTU_SKIP_SCHEMAS=yes YENTU_BASE_DSN='sqlite:sqlite.db'
before_script: 
 - composer install --prefer-dist
 
matrix:
 allow_failures:
  - php: "hhvm"
  
 include:
  - php: "7"
    env: YENTU_DRIVER=mysql YENTU_HOST=localhost YENTU_SKIP_SCHEMAS=yes YENTU_USER=root YENTU_BASE_DSN='mysql:host=localhost' COVERAGE=yes
  - php: "7"
    env: YENTU_DRIVER=postgresql YENTU_HOST=localhost YENTU_USER=postgres YENTU_DEFAULT_SCHEMA=public YENTU_BASE_DSN='pgsql:host=localhost' COVERAGE=yes
  - php: "7"
    env: YENTU_DRIVER=sqlite YENTU_FILE=sqlite.db YENTU_SKIP_SCHEMAS=yes YENTU_BASE_DSN='sqlite:sqlite.db' COVERAGE=yes
 exclude:
  - php: "hhvm"
    env: YENTU_DRIVER=postgresql YENTU_HOST=localhost YENTU_USER=postgres YENTU_DEFAULT_SCHEMA=public YENTU_BASE_DSN='pgsql:host=localhost'
 
services:
 - postgresql
 - mysql

script: vendor/bin/phpunit --coverage-clover coverage.clover --configuration tests/config/travis.xml
after_script: if [ "$COVERAGE" == "yes" ]; then wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --access-token="93e209791d440d1069195255daaa32ce84f96e88ced6d40490b1352dca34f96c" --format=php-clover coverage.clover; fi
